### ISSUE TITLE
All ideas 💡 and Issues 🐛

### ISSUE THREAD

**Issue by Borrus-sudo** [Borrus-sudo/tinypages#104]

**Comment by Borrus-sudo** [comment]
Change gray matter parsing order

**Comment by Borrus-sudo** [comment]
Invalidate top level component when it's importer change

**Comment by Borrus-sudo** [comment]
Try to add support for component error boundary at a component level?

**Comment by Borrus-sudo** [comment]
Scoping css

**Comment by Borrus-sudo** [comment]
Support using UnoCSS and importing icons component in preactjs components

**Comment by Borrus-sudo** [comment]
Fix extra json blob hydration

**Comment by Borrus-sudo** [comment]
Inject script tags later

**Comment by Borrus-sudo** [comment]
Twemoji, circuits, i18n

**Comment by Borrus-sudo** [comment]
Expressions

**Comment by Borrus-sudo** [comment]
Optimize router with radix tree and provide typed definitions

**Comment by Borrus-sudo** [comment]
Make available defaultIconsStyles to the user in config.modules.icons and hide from config.compiler

**Comment by Borrus-sudo** [comment]
Restructure toReturn modules from handleHotUpdate in jsxHMR plugin

**Comment by Borrus-sudo** [comment]
Make pages/ folder structure more like remix

**Comment by Borrus-sudo** [comment]
Add support for `api/` dir which will serve as a way to data fetch ok server during dev and at build time

**Comment by Borrus-sudo** [comment]
Add support for `api/` dir which will serve as a way to data fetch ok server during dev and at build time

**Comment by Borrus-sudo** [comment]
Add support for pwa

**Comment by Borrus-sudo** [comment]
Improve HMR for layout

**Comment by Borrus-sudo** [comment]
Improve client code by not using Suspense for async islands. Instead simple dynamic import and hydrate on fetch approach to be utilised

**Comment by Borrus-sudo** [comment]
Improve Head handling inside components

**Comment by Borrus-sudo** [comment]
Experimental wasm support

**Comment by Borrus-sudo** [comment]
Re-resolve the config file if the config file changed

**Comment by Borrus-sudo** [comment]
Redo typed definitions and make it pure ts type system generated. This should help boost with the server cold start time

**Comment by Borrus-sudo** [comment]
Optimize component looping in the head

**Comment by Borrus-sudo** [comment]
Error boundary bug

**Comment by JacobMGEvans** [comment]
Should make new issues for new tasks, or use milestone feature in GH
